spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_HOST}/realms/master/protocol/openid-connect/certs"
          issuer-uri: "http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_HOST}/realms/local-services-platform"

KEYCLOAK_HOST: localhost
KEYCLOAK_PORT_HOST: 7080